// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU6QQmUJ-S57_ArTer45O954L0pAz47wg',
    appId: '1:501189927069:web:526c506038fad218c4f474',
    messagingSenderId: '501189927069',
    projectId: 'block-todo',
    authDomain: 'block-todo.firebaseapp.com',
    storageBucket: 'block-todo.appspot.com',
    measurementId: 'G-S2YLB15E8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwmRK0j7DUdVHGwUGgaLbwfKnjG0pi3o8',
    appId: '1:501189927069:android:086d8039b758883ec4f474',
    messagingSenderId: '501189927069',
    projectId: 'block-todo',
    storageBucket: 'block-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVmW6Qrcq9wCLD9xhbdM5oq9fyVqEf_Ic',
    appId: '1:501189927069:ios:72d468f85527acfac4f474',
    messagingSenderId: '501189927069',
    projectId: 'block-todo',
    storageBucket: 'block-todo.appspot.com',
    androidClientId: '501189927069-4ieiobbpojnkfu7phuvncf6m9levt58c.apps.googleusercontent.com',
    iosClientId: '501189927069-m9avgeoabu1m0ke4ht2hff3t8rdfd5cr.apps.googleusercontent.com',
    iosBundleId: 'com.sachindapkara.overEngineered',
  );
}
